#! /bin/sh

sxhkd & 
nm-applet &
xrdb merge ~/.Xresources &
picom & 
nitrogen --restore &
~/.config/polybar/launch.sh &
dunst &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10   

bspc config border_width        0 
bspc config window_gap     50 
bsp config presel_feedback_color "#ffffff" 
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config focus_follows_pointer true

bspc config top_padding 30

bspc config focused_border_color "#fabd2f"
bspc config normal_border_color "#968954"
bspc config gapless_monocle false 

bspc rule -a Zathura state=tiled

